"""migration2

Revision ID: 7163d8255c41
Revises: ccf09174701d
Create Date: 2024-08-22 23:18:38.291125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7163d8255c41'
down_revision: Union[str, None] = 'ccf09174701d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('test1', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('test_migration', sa.String(), nullable=True))
    op.add_column('users', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    op.drop_column('messages', 'test_migration')
    op.drop_column('chats', 'test1')
    # ### end Alembic commands ###
